# Generated by Django 3.2.9 on 2021-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField(max_length=250)),
                ('stock', models.IntegerField()),
                ('image', models.CharField(max_length=2050)),
            ],
        ),
    ]
